server:
  port: 18091

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://123.57.73.216:3306/soul_auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      # 连接池配置
      initial-size: 5  # 初始化时建立物理连接的个数
      max-active: 20   # 最大连接池数量
      min-idle: 5      # 最小连接池数量
      max-wait: 60000  # 获取连接时最大等待时间，单位毫秒

